name: longhorn
namespace: longhorn-system

longhorn:
  longhornManager:
    serviceAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9500"
  preUpgradeChecker:
    jobEnabled: false
  persistence:
    defaultClass: false
  defaultSettings:
    allowCollectingLonghornUsageMetrics: false
    defaultReplicaCount: 2
    replicaSoftAntiAffinity: false
    replicaAutoBalance: best-effort
    storageReservedPercentageForDefaultDisk: "0"
    snapshotMaxCount: "250"
    autoCleanupSnapshotWhenDeleteBackup: true
  defaultBackupStore:
    backupTarget: ~
    backupTargetCredentialSecret: b2-secret

encryption:
  secretName: longhorn-crypto

backup:
  secretName: b2-secret
