name: gateway
namespace: gateway-api
gatewayClassName: eg
metallbNamespace: metallb-system
bootstrap:
  enabled: false
integrations:
  certManager: true
  externalSecrets: true
  heartbeats: true

service:
  name: gateway

l2AnnouncementPolicy:
  interface:
    - eth0

loadBalancerIPPool:
  cidr: 192.168.10.51/32
