name: gateway
namespace: gateway
controllerNamespace: envoy-gateway-system
gatewayClassName: eg
metallbNamespace: metallb-system
bootstrap:
  enabled: false
integrations:
  certManager: true
  externalSecrets: true
  heartbeats: true

service:
  name: gateway

tls:
  secretName: tls-certificate

serviceAllocation:
  selectorLabel: gateway.envoyproxy.io/owning-gateway-name

l2AnnouncementPolicy:
  interface:
    - eth0

loadBalancerIPPool:
  cidr: 192.168.10.51/32

envoy-gateway:
  config:
    envoyGateway:
      provider:
        type: Kubernetes
        kubernetes:
          deploy:
            type: GatewayNamespace
