apiVersion: apps.projectsveltos.io/v1alpha1
kind: Cleaner
metadata:
  name: longhorn-trim-jobs
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  schedule: "*/5 * * * *"
  resourcePolicySet:
    resourceSelectors:
      - kind: Job
        group: batch
        version: v1
        namespace: {{ .Values.longhornTrimJobs.namespace }}
        evaluate: |
          function evaluate()
            local result = {}
            result.matching = false

            if obj.metadata.ownerReferences == nil then
              return result
            end

            if obj.status.conditions == nil then
              return result
            end

            for _, owner in ipairs(obj.metadata.ownerReferences) do
              if owner.apiVersion == "batch/v1"
                and owner.kind == "CronJob"
                and owner.name == "trim"
              then
                for _, condition in ipairs(obj.status.conditions) do
                  if (condition.type == "Complete" or condition.type == "Failed")
                    and condition.status == "True"
                  then
                    result.matching = true
                    return result
                  end
                end
              end
            end

            return result
          end
  action: Delete
