apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.waypoint.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
  labels:
    istio.io/dataplane-mode: none
