{{- if not .Values.masterSecret.existingSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    name: {{ .Values.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        annotations:
          reloader.stakater.com/auto: "true"
  data:
    - secretKey: {{ .Values.masterSecret.key }}
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        key: {{ .Values.externalSecret.remoteRef.key }}
        metadataPolicy: None
        property: {{ .Values.externalSecret.remoteRef.property }}
{{- end }}
