{{- $gateway := .Values.gateway | default dict -}}
{{- $gatewayName := $gateway.name | default "gateway" -}}
{{- $gatewayNamespace := $gateway.namespace | default "gateway" -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ index .Values "kubernetes-mcp-server" "fullnameOverride" }}
  namespace: {{ .Values.namespace }}
spec:
  action: ALLOW
  targetRefs:
    - group: ""
      kind: Service
      name: {{ index .Values "kubernetes-mcp-server" "fullnameOverride" }}
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ $gatewayNamespace }}/sa/{{ $gatewayName }}
      to:
        - operation:
            ports:
              - {{ index .Values "kubernetes-mcp-server" "service" "port" | quote }}
