apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kubernetes-mcp-server
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-mcp-server
