apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-telegram-config
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secret-store
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        annotations:
          reloader.stakater.com/auto: "true"
      data:
        alertmanager.yml: |
          global:
            resolve_timeout: 5m
          templates:
            - '/etc/alertmanager/templates/*.tmpl'
          route:
            receiver: telegram
            group_by:
              - alertname
              - namespace
              - severity
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 4h
          receivers:
            - name: telegram
              telegram_configs:
                - bot_token: '{{`{{ .telegram_bot_token }}`}}'
                  chat_id: {{`{{ .telegram_chat_id }}`}}
                  message: '{{`{{ "{{" }} template "otaru.telegram.message" . {{ "}}" }}`}}'
                  send_resolved: true
                  parse_mode: HTML
  data:
    - secretKey: telegram_bot_token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        key: monitoring
        metadataPolicy: None
        property: ALERTMANAGER_TELEGRAM_BOT_TOKEN
    - secretKey: telegram_chat_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        key: monitoring
        metadataPolicy: None
        property: ALERTMANAGER_TELEGRAM_CHAT_ID
