apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: blackbox-scrape-config
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secret-store
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        annotations:
          reloader.stakater.com/auto: "true"
      data:
        blackbox-scrape-config.yml: |
          - job_name: blackbox-https
            metrics_path: /probe
            params:
              module:
                - http_2xx
            static_configs:
              - targets:
                - {{`{{ .gateway_url | quote }}`}}
                - {{`{{ .grafana_url | quote }}`}}
                - {{`{{ .prometheus_url | quote }}`}}
                - {{`{{ .argocd_url | quote }}`}}
                - {{`{{ .umami_url | quote }}`}}
            relabel_configs:
              - source_labels:
                  - __address__
                target_label: __param_target
              - source_labels:
                  - __param_target
                target_label: instance
              - target_label: __address__
                replacement: blackbox:9115
  data:
    - secretKey: gateway_url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        key: monitoring
        metadataPolicy: None
        property: BLACKBOX_PROBE_GATEWAY_URL
    - secretKey: grafana_url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        key: monitoring
        metadataPolicy: None
        property: BLACKBOX_PROBE_GRAFANA_URL
    - secretKey: prometheus_url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        key: monitoring
        metadataPolicy: None
        property: BLACKBOX_PROBE_PROMETHEUS_URL
    - secretKey: argocd_url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        key: monitoring
        metadataPolicy: None
        property: BLACKBOX_PROBE_ARGOCD_URL
    - secretKey: umami_url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        key: monitoring
        metadataPolicy: None
        property: BLACKBOX_PROBE_UMAMI_URL
