name: cloudflare-tunnel
namespace: cloudflare-tunnel

image:
  repository: cloudflare/cloudflared
  tag: "2026.7.2@sha256:4f6655284ab3d252b7f28fedb19fe6c8fc82ee5b1295c20ac74d475e5398a52d"

replicaCount: 2

resources:
  requests:
    cpu: 10m
    memory: 128Mi
    ephemeral-storage: 64Mi
  limits:
    memory: 128Mi
    ephemeral-storage: 64Mi

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              pod: cloudflared
          topologyKey: kubernetes.io/hostname


