name: cloudflare-tunnel
namespace: cloudflare-tunnel

image:
  repository: cloudflare/cloudflared
  tag: "2026.7.0@sha256:5e49861633763e8933475477c20bae6039ed47f32c1d267a34babc347f28f0df"

replicaCount: 2

resources:
  requests:
    cpu: 10m
    memory: 128Mi
    ephemeral-storage: 64Mi
  limits:
    memory: 128Mi
    ephemeral-storage: 64Mi

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              pod: cloudflared
          topologyKey: kubernetes.io/hostname


