{{- $gateway := .Values.gateway | default dict -}}
{{- $gatewayName := $gateway.name | default "gateway" -}}
{{- $gatewayNamespace := $gateway.namespace | default "gateway" -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: argocd-server
  namespace: {{ .Values.namespace }}
spec:
  action: ALLOW
  targetRefs:
    - group: ""
      kind: Service
      name: argocd-server
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ $gatewayNamespace }}/sa/{{ $gatewayName }}
      to:
        - operation:
            ports:
              - "80"
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: argocd-repo-server
  namespace: {{ .Values.namespace }}
spec:
  action: ALLOW
  targetRefs:
    - group: ""
      kind: Service
      name: argocd-repo-server
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ .Values.namespace }}/sa/argocd-application-controller
              - cluster.local/ns/{{ .Values.namespace }}/sa/argocd-applicationset-controller
              - cluster.local/ns/{{ .Values.namespace }}/sa/argocd-server
      to:
        - operation:
            ports:
              - "8081"
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: argocd-redis
  namespace: {{ .Values.namespace }}
spec:
  action: ALLOW
  targetRefs:
    - group: ""
      kind: Service
      name: argocd-redis
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ .Values.namespace }}/sa/argocd-application-controller
              - cluster.local/ns/{{ .Values.namespace }}/sa/argocd-applicationset-controller
              - cluster.local/ns/{{ .Values.namespace }}/sa/argocd-repo-server
              - cluster.local/ns/{{ .Values.namespace }}/sa/argocd-server
      to:
        - operation:
            ports:
              - "6379"
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: argocd-applicationset-controller
  namespace: {{ .Values.namespace }}
spec:
  action: ALLOW
  targetRefs:
    - group: ""
      kind: Service
      name: argocd-applicationset-controller
  rules:
    - to:
        - operation:
            ports:
              - "7000"
