---
- hosts: raspberrypi
  become: true
  vars:
    LB_API_SERVER_IP: 192.168.10.50
    K3S_CHANNEL: stable
    LOCAL_KUBECONFIG_PATH: "{{ lookup('env', 'HOME') }}/.kube/config"

  tasks:
    - name: Install k3s on the first master node
      # Enable anonymous authentication
      # https://stackoverflow.com/questions/74603633/k3s-allow-unauthenticated-access-to-oidc-endpoints
      # All API server arguments need to be passed using the `kube-apiserver-arg` flag
      # https://docs.k3s.io/cli/server#customized-flags-for-kubernetes-processes
      # https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
      # https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL={{ K3S_CHANNEL }} INSTALL_K3S_SKIP_DOWNLOAD=false sh -s - \
          --cluster-init \
          --disable metrics-server \
          --disable servicelb \
          --disable traefik \
          --disable-network-policy \
          --flannel-backend=wireguard-native \
          --secrets-encryption \
          --tls-san {{ LB_API_SERVER_IP }} \
          --tls-san {{ ansible_host }} \
          --write-kubeconfig-mode=644 \
          --kube-apiserver-arg \
          --anonymous-auth=true \
          --kube-apiserver-arg \
          --service-account-issuer=https://oidc.siutsin.com \
          --kube-apiserver-arg \
          --api-audiences=oidc.siutsin.com \
          --kube-apiserver-arg \
          --service-account-jwks-uri=https://oidc.siutsin.com/openid/v1/jwks
      when: "'master' in group_names and inventory_hostname == groups['master'][0]"
      register: first_master_setup
      retries: 3
      delay: 10
      until: first_master_setup.rc == 0

    - name: Read k3s kubeconfig from the first master node
      slurp:
        src: /etc/rancher/k3s/k3s.yaml
      register: first_master_kubeconfig
      delegate_to: "{{ groups['master'][0] }}"
      run_once: true
      changed_when: false

    - name: Copy k3s.yaml to local machine
      copy:
        content: "{{ first_master_kubeconfig.content | b64decode }}"
        dest: "{{ LOCAL_KUBECONFIG_PATH }}"
        mode: '0600'
      delegate_to: localhost
      become: yes
      become_user: simon
      run_once: true
      changed_when: false

    - name: Replace 'default' with 'raspberrypi' in local kube config
      replace:
        path: "{{ LOCAL_KUBECONFIG_PATH }}"
        regexp: 'default'
        replace: 'raspberrypi'
      delegate_to: localhost
      become: yes
      become_user: simon
      run_once: true
      changed_when: false

    - name: Replace '127.0.0.1' with first master IP in local kube config
      replace:
        path: "{{ LOCAL_KUBECONFIG_PATH }}"
        regexp: '127.0.0.1'
        replace: "{{ hostvars[groups['master'][0]]['ansible_host'] }}"
      delegate_to: localhost
      become: yes
      become_user: simon
      run_once: true
      changed_when: false
