apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: {{ .Values.name }}
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/gateway/sa/gateway
      to:
        - operation:
            ports:
              - "3000"
