name: kyverno-policy
namespace: kyverno

clusterSecretStorePolicy:
  enabled: true
  storeName: onepassword-secret-store
  allowedNamespaces:
    argocd:
      - argocd-secret
    blocky:
      - blocky
    changedetection:
      - changedetection
    cloudflare-tunnel:
      - cloudflare-tunnel-credentials
    gateway:
      - cloudflare-acme-verification-secret
      - heartbeats
    home-assistant:
      - heartbeats
    jung2bot:
      - jung2bot
    longhorn-system:
      - b2-secret
      - longhorn-crypto
    monitoring:
      - grafana
      - heartbeats
    teslamate:
      - b2-secret-cloudnative-pg
      - heartbeats
      - teslamate

workloadResourcesPolicy:
  enabled: true
  excludedNamespaces:
    - kube-node-lease
    - kube-public
    - kube-system
    - kyverno
