{{- if .Values.vpa.enabled }}
{{- $namespace := .Release.Namespace | default "onepassword" -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: onepassword-connect
  namespace: {{ $namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: onepassword-connect
  updatePolicy:
    updateMode: InPlaceOrRecreate
  resourcePolicy:
    containerPolicies:
      - containerName: connect-api
        controlledResources: [memory]
        controlledValues: RequestsAndLimits
        minAllowed:
          memory: 16Mi
        maxAllowed:
          memory: 64Mi
      - containerName: connect-sync
        controlledResources: [memory]
        controlledValues: RequestsAndLimits
        minAllowed:
          memory: 16Mi
        maxAllowed:
          memory: 64Mi
{{- end }}
