apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
  data:
    - secretKey: UNIFI_HOST
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        key: {{ .Values.externalSecret.remoteRef.key }}
        metadataPolicy: None
        property: {{ .Values.externalSecret.remoteRef.properties.host }}
    - secretKey: UNIFI_USERNAME
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        key: {{ .Values.externalSecret.remoteRef.key }}
        metadataPolicy: None
        property: {{ .Values.externalSecret.remoteRef.properties.username }}
    - secretKey: UNIFI_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        key: {{ .Values.externalSecret.remoteRef.key }}
        metadataPolicy: None
        property: {{ .Values.externalSecret.remoteRef.properties.password }}
    - secretKey: UNIFI_API_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        key: {{ .Values.externalSecret.remoteRef.key }}
        metadataPolicy: None
        property: {{ .Values.externalSecret.remoteRef.properties.apiKey }}
