apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: k3s-apiserver-loadbalancer-controller-manager
  namespace: k3s-apiserver-loadbalancer-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k3s-apiserver-loadbalancer
