namespace: istio-system

istiod:
  profile: ambient
  pilot:
    env:
      ENABLE_INGRESS_WAYPOINT_ROUTING: "true"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
        ephemeral-storage: 128Mi
      limits:
        memory: 256Mi
        ephemeral-storage: 128Mi
