service:
  clusterIP: 10.43.0.10

deployment:
  replicas: 3
  image:
    repository: rancher/mirrored-coredns-coredns
    tag: "1.14.2@sha256:e7e6440cfd1e919280958f5b5a6ab2b184d385bba774c12ad2a9e1e4183f90d9"
  resources:
    requests:
      cpu: 100m
      memory: 170Mi
      ephemeral-storage: 64Mi
    limits:
      memory: 170Mi
      ephemeral-storage: 64Mi

config:
  corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        cache 30
        loop
        reload
        loadbalance
        forward . /etc/resolv.conf
    }
