service:
  clusterIP: 10.43.0.10

deployment:
  replicas: 3
  image:
    repository: rancher/mirrored-coredns-coredns
    tag: "1.14.3@sha256:b21d26b915e10acb5bc78715c1e8b6047ab2675389b2bcc18b3a6499d90e74c0"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 64Mi
    limits:
      memory: 128Mi
      ephemeral-storage: 64Mi

config:
  corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        cache 30
        loop
        reload
        loadbalance
        forward . /etc/resolv.conf
    }
