service:
  clusterIP: 10.43.0.10

deployment:
  replicas: 3
  image:
    repository: rancher/mirrored-coredns-coredns
    tag: "1.14.6@sha256:900f9c109f7a33545d3c811516e8376df9019147b750f5ce3e254468769176ea"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 64Mi
    limits:
      memory: 128Mi
      ephemeral-storage: 64Mi

config:
  corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        cache 30
        loop
        reload
        loadbalance
        forward . /etc/resolv.conf
    }
