{{- $gateway := .Values.gateway | default dict -}}
{{- $gatewayName := $gateway.name | default "gateway" -}}
{{- $gatewayNamespace := $gateway.namespace | default "gateway" -}}
{{- $heartbeatPrincipal := "cluster.local/ns/heartbeats-operator-system/sa/heartbeats-operator-controller-manager" -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  action: ALLOW
  targetRefs:
    - group: ""
      kind: Service
      name: {{ .Values.name }}
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ $gatewayNamespace }}/sa/{{ $gatewayName }}
              - {{ $heartbeatPrincipal }}
      to:
        - operation:
            ports:
              - "8123"
