apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: home-assistant
spec:
  type: ClusterIP
  ports:
    - port: 8123
      targetPort: http
      protocol: TCP
      name: http
      appProtocol: kubernetes.io/ws
  selector:
    app.kubernetes.io/name: home-assistant
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-coap
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
  type: ClusterIP
  ports:
    - port: 5683
      targetPort: coap
      protocol: UDP
      name: coap
