apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-settings
  namespace: {{ .Values.namespace }}
data:
  settings.yml: |
{{ required "missing settings file files/settings.yml" (.Files.Get "files/settings.yml") | nindent 4 }}
