apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  length: 42
  digits: 5
  symbols: 5
  symbolCharacters: "!&*+"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: "24h"
  target:
    name: {{ .Values.name }}
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: {{ .Values.name }}
