{{- $monitoring := .Values.monitoring | default dict -}}
{{- $prometheusNamespace := $monitoring.namespace | default "monitoring" -}}
{{- $prometheusServiceAccount := $monitoring.prometheusServiceAccount | default "monitoring-prometheus-server" -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: keda-operator
  namespace: keda
spec:
  action: ALLOW
  targetRefs:
    - group: ""
      kind: Service
      name: keda-operator
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ $prometheusNamespace }}/sa/{{ $prometheusServiceAccount }}
              - cluster.local/ns/keda/sa/keda-metrics-server
      to:
        - operation:
            ports:
              - "9666"
