use_default_settings:
  engines:
    keep_only:
      - duckduckgo
      - wikipedia
      - wikidata
      - google cse
search:
  formats:
    - html
    - json
server:
  limiter: false
  public_instance: false
  image_proxy: false
