apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.browser.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: cdp
      port: {{ .Values.browser.port }}
      protocol: TCP
      targetPort: cdp
  selector:
    app.kubernetes.io/name: {{ .Values.browser.name }}
