apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.browser.name }}-profile
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.browser.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.browser.profile.size }}
  storageClassName: {{ .Values.browser.profile.storageClassName }}
