apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.metallbNamespace }}
spec:
  addresses:
    - {{ .Values.loadBalancerIPPool.cidr }}
  serviceAllocation:
    serviceSelectors:
      - matchExpressions:
          - { key: component, operator: In, values: [ apiserver ] }
