apiVersion: monitoring.siutsin.com/v1alpha1
kind: Heartbeat
metadata:
  name: {{ .Values.name }}-heartbeat
  namespace: {{ .Values.namespace }}
spec:
  endpointsSecret:
    name: {{ .Values.name }}-heartbeat
    targetEndpointKey: {{ .Values.name }}-target-endpoint
    healthyEndpointKey: {{ .Values.name }}-healthy-endpoint
    unhealthyEndpointKey: {{ .Values.name }}-unhealthy-endpoint
  expectedStatusCodeRanges:
    - min: 200
      max: 299
  interval: 5m

