apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: {{ .Values.service.name }}
