apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
  labels:
    istio.io/dataplane-mode: none
  name: {{ .Values.controllerNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
  labels:
    istio.io/dataplane-mode: ambient
  name: {{ .Values.namespace }}
