name: changedetection
namespace: changedetection

onepassword:
  key: changedetection
  property: config.yaml

deployment:
  image:
    repository: ghcr.io/dgtlmoon/changedetection.io
    tag: latest@sha256:1cb94f27cac395c90ea4c7a1ea891b241c9a5d5231483961a782312545aadeec
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
      ephemeral-storage: 100Mi
    limits:
      memory: 500Mi
      ephemeral-storage: 100Mi

service:
  port: 5000
  targetPort: 5000

persistence:
  claimName: changedetection-pvc
  mountPath: /datastore
