name: changedetection
namespace: changedetection

onepassword:
  key: changedetection
  property: config.yaml

deployment:
  image:
    repository: ghcr.io/dgtlmoon/changedetection.io
    tag: latest@sha256:b632a9fb6be702fb859e02cd5cac5de7a7466ce1e97f5f5347a1d012c0720108
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
      ephemeral-storage: 100Mi
    limits:
      memory: 500Mi
      ephemeral-storage: 100Mi

service:
  port: 5000
  targetPort: 5000

persistence:
  claimName: changedetection-pvc
  mountPath: /datastore
