{{- range .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
{{- if not (has . ($.Values.ambientLabelExclusions | default list)) }}
  labels:
{{- $.Values.labels | toYaml | nindent 4 }}
{{- end }}
  name: {{ . }}
{{- end }}
