apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.deployment.ports.http }}
      targetPort: {{ .Values.deployment.ports.http }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-dns
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
  type: ClusterIP
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
