_shared:
  preferredPodAntiAffinity: &preferredPodAntiAffinity
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname

cert-manager:
  affinity:
    <<: *preferredPodAntiAffinity
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
      ephemeral-storage: 64Mi
    limits:
      memory: 128Mi
      ephemeral-storage: 64Mi
  cainjector:
    affinity:
      <<: *preferredPodAntiAffinity
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
        ephemeral-storage: 64Mi
      limits:
        memory: 128Mi
        ephemeral-storage: 64Mi
  webhook:
    affinity:
      <<: *preferredPodAntiAffinity
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
        ephemeral-storage: 64Mi
      limits:
        memory: 64Mi
        ephemeral-storage: 64Mi
  startupapicheck:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
        ephemeral-storage: 64Mi
      limits:
        memory: 64Mi
        ephemeral-storage: 64Mi
  enableCertificateOwnerRef: true
  installCRDs: true
