apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: raspberrypi-00
  namespace: {{ .Values.namespace }}
spec:
  allowScheduling: true
  disks:
    default-disk-a6c00bbc1be864c4:
      allowScheduling: true
      diskType: filesystem
      evictionRequested: false
      path: /var/lib/longhorn/
  name: raspberrypi-00
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: raspberrypi-01
  namespace: {{ .Values.namespace }}
spec:
  allowScheduling: true
  disks:
    default-disk-a6c00bbc1be864c4:
      allowScheduling: true
      diskType: filesystem
      evictionRequested: false
      path: /var/lib/longhorn/
  name: raspberrypi-01
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: raspberrypi-03
  namespace: {{ .Values.namespace }}
spec:
  allowScheduling: false
  name: raspberrypi-03
