reloader:
  reloader:
    deployment:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
          ephemeral-storage: 64Mi
        limits:
          memory: 64Mi
          ephemeral-storage: 64Mi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node.siutsin.com/storage-tier
                    operator: In
                    values:
                      - sd-card
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
        tolerations:
          - key: node.siutsin.com/storage-tier
            operator: Equal
            value: sd-card
            effect: PreferNoSchedule
