---
# rpi
- import_playbook: rpi/000-disable-write-log-to-disk.yaml
- import_playbook: rpi/001-packages.yaml
- import_playbook: rpi/002-waveshare-poe-hat.yaml
- import_playbook: rpi/003-networking.yaml
- import_playbook: rpi/004-cgroup.yaml
- import_playbook: rpi/005-brcmfmac-options.yaml
# k3s
- import_playbook: k3s/000-init-cluster.yaml
- import_playbook: k3s/001-cni.yaml
- import_playbook: k3s/002-nodes.yaml
- import_playbook: k3s/003-bootstrap.yaml
