{{- if .Values.connector.enabled }}
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: {{ .Values.connector.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hostnamePrefix: {{ .Values.connector.hostnamePrefix | quote }}
  exitNode: {{ .Values.connector.exitNode | default false }}
  replicas: {{ .Values.connector.replicas | default 1 }}
  {{- if .Values.connector.proxyClass }}
  proxyClass: {{ .Values.connector.proxyClass | quote }}
  {{- end }}
  subnetRouter:
    advertiseRoutes:
      {{- toYaml .Values.connector.advertiseRoutes | nindent 6 }}
{{- end }}
