apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        key: {{ .Values.externalSecret.remoteRef.key | quote }}
        metadataPolicy: None
        property: client_id
    - secretKey: client_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        key: {{ .Values.externalSecret.remoteRef.key | quote }}
        metadataPolicy: None
        property: client_secret
