name: k8s-mcp
namespace: kubernetes-mcp-server

service:
  port: 8080

kubernetes-mcp-server:
  ingress:
    enabled: false
  resources:
    limits:
      cpu: ~
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: volume
                operator: NotIn
                values:
                  - "true"
