name: k8s-mcp
namespace: kubernetes-mcp-server

kubernetes-mcp-server:
  ingress:
    enabled: false
  service:
    port: 8080
  fullnameOverride: kubernetes-mcp-server
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
      ephemeral-storage: 64Mi
    limits:
      memory: 128Mi
      ephemeral-storage: 64Mi
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: volume
                operator: NotIn
                values:
                  - "true"
