name: amazon-eks-pod-identity-webhook
namespace: default

pod-identity-webhook:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
      ephemeral-storage: 64Mi
    limits:
      memory: 64Mi
      ephemeral-storage: 64Mi
  config:
    defaultAwsRegion: eu-west-1
    tokenAudience: oidc.siutsin.com
