name: amazon-eks-pod-identity-webhook
namespace: default

amazon-eks-pod-identity-webhook:
  replicaCount: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  mutatingWebhook:
    failurePolicy: Fail
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - amazon-eks-pod-identity-webhook
          topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 64Mi
  config:
    defaultAwsRegion: eu-west-1
    tokenAudience: oidc.siutsin.com
