name: excalidraw
namespace: excalidraw

deployment:
  image:
    repository: docker.io/excalidraw/excalidraw
    tag: latest@sha256:20ffa04668e19616bb0c1b3632849e5cd96e0bc7a1336b73d9d072667f2c2854

service:
  port: 80
  targetPort: 80
