apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
    istio.io/use-waypoint-namespace: istio-waypoints
    istio.io/ingress-use-waypoint: "true"
  name: {{ .Values.namespace }}
