namespace: k8s-cleaner

excludeNamespaces: &excludeNamespaces
  - gateway-api
  - istio-system
  - kube-system
  - longhorn-system
  - metallb-system

repave:
  maxAgeSeconds: 259200
  excludeNamespaces: *excludeNamespaces

failedPods:
  excludeNamespaces: *excludeNamespaces

k8s-cleaner:
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
        ephemeral-storage: 64Mi
      limits:
        memory: 64Mi
        ephemeral-storage: 64Mi
  affinity:
