apiVersion: v2
name: monitoring
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
icon: https://raw.githubusercontent.com/helm/helm/main/assets/images/helm.svg
dependencies:
- name: prometheus
  version: 29.2.1
  repository: https://prometheus-community.github.io/helm-charts
- name: victoria-metrics-cluster
  version: 0.41.2
  repository: https://victoriametrics.github.io/helm-charts
- name: victoria-metrics-agent
  version: 0.38.0
  repository: https://victoriametrics.github.io/helm-charts
- name: victoria-metrics-alert
  version: 0.39.0
  repository: https://victoriametrics.github.io/helm-charts
- name: loki
  version: 7.0.0
  repository: https://grafana.github.io/helm-charts
- name: fluent-bit
  version: 0.57.3
  repository: https://fluent.github.io/helm-charts
- name: grafana
  version: 10.5.15
  repository: https://grafana.github.io/helm-charts
