all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    # Nodes
    node00:
      hosts:
        raspberrypi-00.local:
          ansible_host: 192.168.10.60
    node01:
      hosts:
        raspberrypi-01.local:
          ansible_host: 192.168.10.61
    node02:
      hosts:
        raspberrypi-02.local:
          ansible_host: 192.168.10.62
    node03:
      hosts:
        raspberrypi-03.local:
          ansible_host: 192.168.10.63
    node20:
      hosts:
        nuc-00.local:
          ansible_host: 192.168.10.80
          ansible_ssh_user: ubuntu
          luks_root_disk: /dev/sda
          luks_boot_partition: /dev/sda2
          luks_root_partition: /dev/sda3
          luks_mapper_name: dm_crypt-0
          luks_initramfs_iface: eno1
          luks_initramfs_ip: 192.168.10.80
          luks_unlock_authorized_keys_src: /home/ubuntu/.ssh/authorized_keys
    # Groups
    master:
      children:
        node00: { }
        node01: { }
        node02: { }
    rpi5:
      children:
        node00: { }
        node01: { }
        node02: { }
        node03: { }
    worker:
      children:
        node03: { }
        node20: { }
    k3s_cluster:
      children:
        master: { }
        worker: { }
    luks_root_nodes:
      vars:
        luks_enabled: true
        luks_root_disk: /dev/nvme0n1
        luks_boot_partition: /dev/nvme0n1p1
        luks_root_partition: /dev/nvme0n1p2
        luks_mapper_name: cryptroot
        luks_initramfs_iface: eth0
        luks_initramfs_gateway: 192.168.10.1
        luks_initramfs_netmask: 255.255.255.0
        luks_initramfs_dns: 192.168.10.1
        luks_dropbear_port: 1024
        luks_unlock_authorized_keys_src: /home/pi/.ssh/authorized_keys
        luks_passphrase_vault_var_name: otaru_luks_password
      children:
        node00: { }
        node01: { }
        node02: { }
        node03: { }
        node20: { }
    raspberrypi:
      vars:
        ansible_ssh_user: pi
      children:
        rpi5: { }
