all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    # Nodes
    node00:
      hosts:
        raspberrypi-00.local:
          ansible_host: 192.168.10.60
    node01:
      hosts:
        raspberrypi-01.local:
          ansible_host: 192.168.10.61
    node02:
      hosts:
        raspberrypi-02.local:
          ansible_host: 192.168.10.62
    node03:
      hosts:
        raspberrypi-03.local:
          ansible_host: 192.168.10.63
    # Groups
    master:
      children:
        node00: { }
        node01: { }
        node02: { }
    rpi5:
      children:
        node00: { }
        node01: { }
        node02: { }
    worker:
      children:
        node03: { }
    waveshare_poe_hat:
      children:
        node03: { }
    luks_root_candidates:
      vars:
        luks_root_disk: /dev/nvme0n1
        luks_boot_partition: /dev/nvme0n1p1
        luks_root_partition: /dev/nvme0n1p2
        luks_mapper_name: cryptroot
        luks_initramfs_iface: eth0
        luks_initramfs_gateway: 192.168.10.1
        luks_initramfs_netmask: 255.255.255.0
        luks_initramfs_dns: 192.168.10.1
        luks_dropbear_port: 1024
        luks_unlock_authorized_keys_src: /home/pi/.ssh/authorized_keys
        luks_passphrase_vault_var_name: otaru_luks_password
      children:
        node00: { }
        node01: { }
        node02: { }
    luks_root_development:
      vars:
        luks_enabled: true
      children:
        node01: { }
    luks_root_current_target:
      children:
        node00: { }
    raspberrypi:
      vars:
        ansible_ssh_user: pi
      children:
        master: { }
        worker: { }
