all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    # Nodes
    node00:
      hosts:
        raspberrypi-00.local:
          ansible_ssh_user: pi
          ansible_host: 192.168.1.60
          ansible_host_eth: 192.168.1.60
          ansible_host_wifi: 192.168.1.80
          ansible_host_wifi_gateway: 192.168.1.1
    node01:
      hosts:
        raspberrypi-01.local:
          ansible_ssh_user: pi
          ansible_host: 192.168.1.61
          ansible_host_eth: 192.168.1.61
          ansible_host_wifi: 192.168.1.81
          ansible_host_wifi_gateway: 192.168.1.1
    node02:
      hosts:
        raspberrypi-02.local:
          ansible_ssh_user: pi
          ansible_host: 192.168.1.62
          ansible_host_eth: 192.168.1.62
          ansible_host_wifi: 192.168.1.82
          ansible_host_wifi_gateway: 192.168.1.1
    node03:
      hosts:
        raspberrypi-03.local:
          ansible_ssh_user: pi
          ansible_host: 192.168.1.63
          ansible_host_eth: 192.168.1.63
          ansible_host_wifi: 192.168.1.83
          ansible_host_wifi_gateway: 192.168.1.1
    etcd:
      hosts:
        ubuntu.local:
          ansible_ssh_user: ubuntu
          ansible_host: 192.168.1.52
    # Groups
    master:
      children:
        node00: { }
        node01: { }
        node02: { }
        node03: { }
    worker:
      children: { }
    waveshare_poe_hat:
      children:
        node00: { }
        node01: { }
    pineberry_pi_hatdrive:
      children:
        node03: { }
    volume:
      children:
        node02: { }
        node03: { }
    raspberrypi:
      children:
        master: { }
        worker: { }
