{{- $gateway := .Values.gateway | default dict -}}
{{- $gatewayName := $gateway.name | default "gateway" -}}
{{- $gatewayNamespace := $gateway.namespace | default "gateway" -}}
{{- $databaseName := .Values.database.secretName -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: hydra-public
  namespace: {{ .Values.namespace }}
spec:
  action: ALLOW
  targetRefs:
    - group: ""
      kind: Service
      name: hydra-public
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ $gatewayNamespace }}/sa/{{ $gatewayName }}
      to:
        - operation:
            ports:
              - "4444"
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: hydra-admin
  namespace: {{ .Values.namespace }}
spec:
  action: ALLOW
  targetRefs:
    - group: ""
      kind: Service
      name: hydra-admin
  {{- if .Values.clientController.enabled }}
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ .Values.namespace }}/sa/{{ .Values.clientController.serviceAccountName }}
      to:
        - operation:
            ports:
              - "4445"
  {{- else }}
  rules: []
  {{- end }}
{{- range $suffix := list "r" "ro" "rw" }}
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ printf "%s-%s" $databaseName $suffix }}
  namespace: {{ $.Values.namespace }}
spec:
  action: ALLOW
  targetRefs:
    - group: ""
      kind: Service
      name: {{ printf "%s-%s" $databaseName $suffix }}
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ $.Values.namespace }}/sa/default
              - cluster.local/ns/{{ $.Values.namespace }}/sa/hydra
              - cluster.local/ns/{{ $.Values.namespace }}/sa/hydra-job
              - cluster.local/ns/{{ $.Values.namespace }}/sa/{{ $databaseName }}
      to:
        - operation:
            ports:
              - "5432"
{{- end }}
