apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.systemSecret.name }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.systemSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.systemSecret.secretStoreRef.kind }}
    name: {{ .Values.systemSecret.secretStoreRef.name }}
  target:
    name: {{ .Values.systemSecret.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        annotations:
          reloader.stakater.com/auto: "true"
  data:
    - secretKey: secretsSystem
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        key: {{ .Values.systemSecret.remoteRef.key }}
        metadataPolicy: None
        property: hydraSecretsSystem
    - secretKey: secretsCookie
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        key: {{ .Values.systemSecret.remoteRef.key }}
        metadataPolicy: None
        property: hydraSecretsCookie
