{{- if .Values.oauthClient.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.oauthClient.secretName }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: {{ .Values.oauthClient.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.oauthClient.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.oauthClient.externalSecret.secretStoreRef.name }}
  target:
    name: {{ .Values.oauthClient.secretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        CLIENT_ID: {{ .Values.oauthClient.id | quote }}
        CLIENT_SECRET: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        key: {{ .Values.oauthClient.externalSecret.remoteRef.key | quote }}
        metadataPolicy: None
        property: {{ .Values.oauthClient.externalSecret.remoteRef.property | quote }}
{{- end }}
