_shared:
  resources: &resources
    requests:
      cpu: 50m
      memory: 128Mi
      ephemeral-storage: 64Mi
    limits:
      memory: 128Mi
      ephemeral-storage: 64Mi
  preferredPodAntiAffinity: &preferredPodAntiAffinity
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname

integrations:
  clusterSecretStore: true

external-secrets:
  affinity:
    <<: *preferredPodAntiAffinity
  resources: *resources
  webhook:
    affinity:
      <<: *preferredPodAntiAffinity
    resources: *resources
  certController:
    affinity:
      <<: *preferredPodAntiAffinity
    resources: *resources
  global:
    affinity:
      <<: *preferredPodAntiAffinity
