apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: snapshot-controller
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: snapshot-controller
