---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: heartbeats-operator-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.siutsin.com
    resources:
      - heartbeats
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.siutsin.com
    resources:
      - heartbeats/status
    verbs:
      - get
      - patch
      - update
