apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: heartbeats-operator
    control-plane: controller-manager
    istio.io/dataplane-mode: ambient
  name: heartbeats-operator-system
