apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: heartbeats-operator
    app.kubernetes.io/version: v0.155.0
    control-plane: controller-manager
  name: heartbeats-operator-system
