apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: heartbeats-operator-controller-manager
  namespace: heartbeats-operator-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: heartbeats-operator
