controller:
  image:
    # Upstream v8.6.0 deploys this v8.5.0 controller image.
    repository: registry.k8s.io/sig-storage/snapshot-controller
    tag: v8.5.0@sha256:74ca61ab13e978f03cf0f336a607281d15f04cda0a38a881306365473b28a3d8
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
      ephemeral-storage: 32Mi
    limits:
      memory: 64Mi
      ephemeral-storage: 32Mi
