{{- if .Values.integrations.certManager }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-repo-server-tls
  namespace: {{ .Values.namespace }}
spec:
  secretName: argocd-repo-server-tls
  duration: 8760h
  renewBefore: 720h
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: argocd-repo-server
  dnsNames:
    - argocd-repo-server
    - argocd-repo-server.{{ .Values.namespace }}
    - argocd-repo-server.{{ .Values.namespace }}.svc
    - argocd-repo-server.{{ .Values.namespace }}.svc.cluster.local
  usages:
    - server auth
{{- end }}
