name: cloudnative-pg-clusters
namespace: cnpg-system

backup:
  enabled: true
  b2:
    bucket: ~
    endpoint: ~

defaults:
  cluster:
    affinity:
      podAntiAffinityType: preferred
    instances: 1
    enablePDB: true
    failoverDelay: 0
    imageName: ghcr.io/cloudnative-pg/postgresql:17.4
    logLevel: info
    maxSyncReplicas: 0
    minSyncReplicas: 0
    monitoring:
      customQueriesConfigMap:
        - name: cnpg-default-monitoring
          key: queries
      disableDefaultQueries: false
      enablePodMonitor: false
    postgresGID: 26
    postgresUID: 26
    primaryUpdateMethod: restart
    primaryUpdateStrategy: unsupervised
    replicationSlots:
      highAvailability:
        enabled: true
        slotPrefix: _cnpg_
      synchronizeReplicas:
        enabled: true
      updateInterval: 30
    resources: {}
    smartShutdownTimeout: 180
    startDelay: 3600
    stopDelay: 1800
    storage:
      resizeInUseVolumes: true
      size: 5Gi
      storageClass: longhorn-crypto-global
    switchoverDelay: 3600
    backup:
      target: primary
      retentionPolicy: 1d
    plugins:
      - enabled: true
        isWALArchiver: false
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: b2-backup
    postgresql: &postgresql
      parameters:
        archive_mode: "on"
        archive_timeout: 5min
        dynamic_shared_memory_type: posix
        full_page_writes: "on"
        log_destination: csvlog
        log_directory: /controller/log
        log_filename: postgres
        log_rotation_age: "0"
        log_rotation_size: "0"
        log_truncate_on_rotation: "false"
        logging_collector: "on"
        max_parallel_workers: "32"
        max_replication_slots: "32"
        max_worker_processes: "32"
        shared_memory_type: mmap
        shared_preload_libraries: ""
        ssl_max_protocol_version: TLSv1.3
        ssl_min_protocol_version: TLSv1.3
        wal_keep_size: 512MB
        wal_level: logical
        wal_log_hints: "on"
        wal_receiver_timeout: 5s
        wal_sender_timeout: 5s
      pg_hba: # Default pg_hba configuration for certificate-only authentication
        - hostssl all all 0.0.0.0/0 cert
        - hostssl all all ::0/0 cert
      syncReplicaElectionConstraint:
        enabled: false
  scheduledBackup:
    enabled: true
    schedule: "0 0 */3 * * *"
  objectStore:
    retentionPolicy: 1d

clusters:
  # https://cloudnative-pg.io/documentation/current/recovery/#restoring-into-a-cluster-with-a-backup-section
  # Avoid reusing the same ObjectStore configuration for both backup and recovery in the same cluster. If you must, ensure that each cluster uses a unique serverName
  # to prevent accidental overwrites of backup data.

  teslamate:
    clusterName: teslamate-20260412-0619
    affinity:
      podAntiAffinityType: required
    instances: 2
    minSyncReplicas: 1
    maxSyncReplicas: 1
    labels:
      cnpg.io/reload: "true"
      cnpg.io/skipEmptyWalArchiveCheck: "true"
    namespace: teslamate
    postgresql:
      <<: *postgresql
      pg_hba: # Use password authentication
        - hostssl all all 0.0.0.0/0 scram-sha-256
        - hostssl all all ::0/0 scram-sha-256
    enableSuperuserAccess: true
    managed:
      roles:
        - name: app
          ensure: present
          superuser: true
          login: true
          connectionLimit: -1
          inherit: true
    test:
      enabled: true
      query: SELECT name FROM cars;
    bootstrap:
      recovery:
        source: teslamate-backup-source
        database: app
        owner: app
    externalClusters:
      - name: teslamate-backup-source
        plugin:
          enabled: true
          isWALArchiver: false
          name: barman-cloud.cloudnative-pg.io
          parameters:
            barmanObjectName: b2-backup
            serverName: teslamate-20251024-0015
