apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        annotations:
          reloader.stakater.com/auto: "true"
  data:
    {{- range $secretKey, $property := .Values.externalSecret.remoteRef.properties }}
    - secretKey: {{ $secretKey }}
      remoteRef:
        key: {{ $.Values.externalSecret.remoteRef.key }}
        property: {{ $property }}
    {{- end }}
