metrics-server:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
      ephemeral-storage: 64Mi
    limits:
      memory: 128Mi
      ephemeral-storage: 64Mi
  replicas: 2
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: metrics-server
            topologyKey: kubernetes.io/hostname
